Feature/#3 scrate test cases作成
imahiro2199/AtCoder pull request #7
Opened 2022-06-12 14:45 UTC by imahiro2199

Close #3 

## 概要
`SCRAPE_TEST_CASES` を実装
動作の詳細は[README](https://github.com/imahiro2199/AtCoder/blob/feature/%233_SCRATE_TEST_CASES%E4%BD%9C%E6%88%90/scripts/SCRAPE_TEST_CASES/README.md)を参照

## Test
動作前提を満たすときにテストケースが作成されること

2022-06-17 02:55 UTC, yuya0405 commented on README.md
> +現在のところAtCoderの完成したコードを登録する予定はない(AtCoder上で閲覧できるため)。
毎回GitHubにコードをpushするのは煩わしいかもしれないけど、今後、ライブラリ化したコードを纏めておくと、試験中に便利かもしれないよ？

例：
https://github.com/yuya0405/AtCoderLibrary

2022-06-17 13:50 UTC, imahiro2199 commented on README.md
> +現在のところAtCoderの完成したコードを登録する予定はない(AtCoder上で閲覧できるため)。
残念ながら現在は例示されたようなライブラリ化されたコードは存在しないので、対応しません。
ただし、ライブラリ化されたコードを作成した場合は別途検討します。

2022-06-18 06:22 UTC, yuya0405 requested changes
なんかCryptoのパッケージのせいで動作しない

2022-06-18 06:22 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
このパッケージが悪さをしているのか、
python (SCRAPE_TEST_CASESまでのパス/)scrape_test_cases.py [url]
を実行した際にエラー

以下も試したが、同じくエラー
```
pip install PyCrypto
```

エラーログ
```
AtCoder/scripts/test_case/abc255 on  feature/#3_SCRATE_TEST_CASES作成  | yuya9445@gmail.com |
❯ python3 ../../SCRAPE_TEST_CASES/scrape_test_cases.py                                                                                                                                                      INSERT
Traceback (most recent call last):
  File "../../SCRAPE_TEST_CASES/scrape_test_cases.py", line 10, in <module>
    import config
  File "/Users/wisdom/Desktop/AtCoder/scripts/SCRAPE_TEST_CASES/config.py", line 7, in <module>
    import login_info_control as lg_ct
  File "/Users/wisdom/Desktop/AtCoder/scripts/SCRAPE_TEST_CASES/login_info_control.py", line 3, in <module>
    from Crypto.PublicKey import RSA
  File "/usr/local/lib/python3.7/site-packages/Crypto/PublicKey/RSA.py", line 585
    except ValueError, IndexError:
                     ^
SyntaxError: invalid syntax
```

参考資料：
https://github.com/pycrypto/pycrypto/issues/327
https://discuss.redash.io/t/an-error-occurs-redash-docker-on-startup/10608

2022-06-18 06:36 UTC, imahiro2199 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
確認します。
すぐに解決できない可能性があります。
ログイン情報の登録以降の部分の動作確認をお願いします。
`config.py` の以下の部分をユーザ名とパスワードを直接指定するように書き換えるとエラーの部分を回避できると思います。
```python
# Be careful not to expose this file if you set USERNAME or PASSWORD directly.
 USERNAME, PASSWORD = lg_ct.ecd_msg(KEY_PATH, USERNAME_PATH, PASSWORD_PATH)
```

2022-06-18 06:48 UTC, imahiro2199 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
指定パッケージを間違えた可能性があります。
`pycrypto` をアンインストールの上 `pycryptodome` をインストールして試してみてください。
```shell
pip install pycryptodome
```

2022-06-18 10:37 UTC, yuya0405 requested changes
コメント返しました
まだダメです

2022-06-18 10:37 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
今度はパッケージのパスが通ってない
修正の必要ありそう

```
python3 ../../SCRAPE_TEST_CASES/scrape_test_cases.py
Traceback (most recent call last):
  File "../../SCRAPE_TEST_CASES/scrape_test_cases.py", line 10, in <module>
    import config
  File "/Users/wisdom/Desktop/AtCoder/scripts/SCRAPE_TEST_CASES/config.py", line 7, in <module>
    import login_info_control as lg_ct
  File "/Users/wisdom/Desktop/AtCoder/scripts/SCRAPE_TEST_CASES/login_info_control.py", line 3, in <module>
    from Crypto.PublicKey import RSA
ImportError: cannot import name 'RSA' from 'Crypto.PublicKey' (unknown location)
```

2022-06-19 02:40 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
pyenvで新しい仮想環境を立てたら解決

2022-06-19 02:43 UTC, yuya0405 requested changes
また別のところでエラー

2022-06-19 02:43 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/login_info_control.py
> +    f.write(prv_key.export_key().decode())
この行で今度はエラー
export_keyっていうライブラリが読み込めてない

```
AtCoder/scripts/test_case/abc255 on  feature/#3_SCRATE_TEST_CASES作成 [1?] via 🐍 v3.7.13 (py37env)  | yuya9445@gmail.com |
❯ python3 ../../SCRAPE_TEST_CASES/login_info_control.py                                                                                                                                                     INSERT
Generate setting files
- type your username...
username: octet9445
- type your password....
password:
Traceback (most recent call last):
  File "../../SCRAPE_TEST_CASES/login_info_control.py", line 85, in <module>
    gen_config_files()
  File "../../SCRAPE_TEST_CASES/login_info_control.py", line 47, in gen_config_files
    f.write(prv_key.export_key().decode())
  File "/Users/wisdom/Desktop/AtCoder/scripts/test_case/py37env/lib/python3.7/site-packages/Crypto/PublicKey/RSA.py", line 126, in __getattr__
    raise AttributeError("%s object has no %r attribute" % (self.__class__.__name__, attrname,))
AttributeError: _RSAobj object has no 'export_key' attribute
```

2022-06-19 02:48 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/login_info_control.py
> +    f.write(prv_key.export_key().decode())
解決しました

やっぱり（macの場合は？？？）Pycryptoじゃなくて、やっぱりPycryptodomeなのかな？

2022-06-19 02:50 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/login_info_control.py
> +    f.write(prv_key.export_key().decode())
今度はparserのlibraryがないって怒られた

```
AtCoder/scripts/test_case/abc255 on  feature/#3_SCRATE_TEST_CASES作成 [1?] via 🐍 v3.7.13 (py37env)  | yuya9445@gmail.com |
❯ python3 ../../SCRAPE_TEST_CASES/scrape_test_cases.py                                                                                                                                                      INSERT
https://atcoder.jp/contests/abc255
Login to https://atcoder.jp/login
Traceback (most recent call last):
  File "../../SCRAPE_TEST_CASES/scrape_test_cases.py", line 131, in <module>
    main()
  File "../../SCRAPE_TEST_CASES/scrape_test_cases.py", line 122, in main
    session = login(LOGIN_URL, session)
  File "../../SCRAPE_TEST_CASES/scrape_test_cases.py", line 87, in login
    login_lxml   = BeautifulSoup(login_page.text, 'lxml')
  File "/Users/wisdom/Desktop/AtCoder/scripts/test_case/py37env/lib/python3.7/site-packages/bs4/__init__.py", line 251, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

2022-06-19 02:52 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/login_info_control.py
> +    f.write(prv_key.export_key().decode())
依存パッケージをインストールして解決

```
pip3 install lxml
```

2022-06-19 02:54 UTC, yuya0405 requested changes
依存ライブラリのところをREADMEに追記してもらえれば、後はLGTMですー

2022-06-19 02:54 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
macの場合（？）は

```
pip install Pycryptodome
```

これに加え、

```
pip install lxml
```

も必要だった

2022-06-19 09:01 UTC, imahiro2199 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
[ac4a1d9](https://github.com/imahiro2199/AtCoder/pull/7/commits/ac4a1d923361e7fcd0e18fd2f38851dc776ad510) にて修正しました。
いずれも間違い・記入漏れでした。
確認をお願いします。

2022-06-19 09:23 UTC, yuya0405 commented on scripts/SCRAPE_TEST_CASES/README.md
> +        ```
LGTM

2022-06-19 09:24 UTC, yuya0405 approved these changes

2022-06-19 13:25 UTC, youkiawk commented
動作確認オッケーです

2022-06-19 14:30 UTC, Shuj1029 approved these changes
動作確認完了しました。

2022-06-19 14:33 UTC, youkiawk approved these changes

2022-06-19 14:34 UTC, merged