Feature/#5 run all test cases作成
imahiro2199/AtCoder pull request #8
Opened 2022-06-19 15:39 UTC by imahiro2199

Close #5 

## 概要
`RUN_ALL_TEST_CASES` を実装 (とりあえず動作Ver)
動作の詳細は[README](https://github.com/imahiro2199/AtCoder/tree/feature/%235_RUN_ALL_TEST_CASES%E4%BD%9C%E6%88%90/scripts/RUN_ALL_TEST_CASES)を参照

## Test
動作前提を満たすときにテストケースが作成されること

2022-06-19 15:40 UTC, imahiro2199 commented
追加機能の要望があれば本Pull requestにてコメントください。
採用されればApproved後にIssueを立てて実装します。

2022-06-25 08:55 UTC, youkiawk requested changes
WAのとき常にcase1のInputが表示されてしまいます。
修正案をコメントしました。

2022-06-25 08:55 UTC, youkiawk commented on scripts/RUN_ALL_TEST_CASES/run_all_test_cases.py
> +                    print('\n'.join(input_strs[0].splitlines()))
```suggestion
                    print('\n'.join(input_strs[i].splitlines()))
```

2022-06-25 08:55 UTC, youkiawk commented on scripts/RUN_ALL_TEST_CASES/run_all_test_cases.py
> +                    print('\n'.join(output_strs[0].splitlines()))
```suggestion
                    print('\n'.join(output_strs[i].splitlines()))
```

2022-06-25 09:20 UTC, imahiro2199 commented
> WAのとき常にcase1のInputが表示されてしまいます。
> 
> 修正案をコメントしました。

Suggestionを採用しました。
確認ありがとうございます。

2022-06-25 10:00 UTC, yuya0405 approved these changes
LGTMです

2022-06-25 10:00 UTC, yuya0405 commented on scripts/RUN_ALL_TEST_CASES/README.md
> +    ```
これって何で手動配置なんですか？

2022-06-25 14:30 UTC, youkiawk approved these changes
OKです

2022-06-25 14:51 UTC, imahiro2199 commented on scripts/RUN_ALL_TEST_CASES/README.md
> +    ```
本リポジトリ環境では手動配置する必要はありません。
一方で、`RUN_ALL_TEST_CASES` をコピー(or 移動)して使用する際には `LIB` も同様の対応が必要なため、注意書きとして書いています。

もちろん、この構成がいいのかは意見が分かれるところかもしれませんが (`LIB` を `RUN_ALL_TEST_CASES` 内に配置するべき、など)

2022-06-25 14:57 UTC, imahiro2199 commented on scripts/RUN_ALL_TEST_CASES/README.md
> +    ```
今回は `RUN_ALL_TEST_CASES` と共通して使用している関数があるため、どちらからもアクセスできるように同階層に配置しています。
 `LIB` の二重管理を避けることを目的としています。

2022-06-25 21:06 UTC, yuya0405 commented on scripts/RUN_ALL_TEST_CASES/README.md
> +    ```
了解

2022-06-26 05:38 UTC, Shuj1029 approved these changes
動作確認完了

2022-06-26 08:18 UTC, merged